CREATE TABLE IF NOT EXISTS jobs {
    id BIGSERIAL PRIMARY KEY NOT NULL.
    nam VARCHAR(255) NOT NULL DEFAULT '',
    duration INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
}